services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - ephimail-network
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8081:8080

  backend:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.backend
    volumes:
      - ./:/app
    ports:
      - 8080:80  # Web interface
      - 2525:25  # SMTP service
    depends_on:
      - redis
    networks:
      - ephimail-network
    environment:
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - MAIL_ADDRESS=0.0.0.0
      - MAIL_PORT=25
      - WEB_ADDRESS=0.0.0.0
      - WEB_PORT=80
      - ALLOWED_DOMAINS=chevuoida.me
      - EMAIL_TTL=24
      - MAX_RESERVATION_DAYS=7
      - TZ=UTC

networks:
  ephimail-network:
    driver: bridge