#!/bin/bash

IFS='' read -r -d '' DATA <<'EOF'
EHLO localhost
MAIL FROM:<root@nsa.gov>
RCPT TO:<root@localhost>
DATA
MIME-Version: 1.0
From: Lo Zio <antani@example.com>
Date: Sat, 24 Feb 2024 17:43:20 +0100
Subject: Ciao
To: root@localhost

porcodio
.
EOF

echo "$DATA" | "nc" -C -v "localhost" "1025"