#!/bin/bash

IFS='' read -r -d '' DATA <<'EOF'
EHLO localhost
MAIL FROM:<root@nsa.gov>
RCPT TO:<flawless-ad@chevuoida.me>
DATA
MIME-Version: 1.0
From: Lo Zio <antani@example.com>
Date: Sat, 24 Feb 2024 17:43:20 +0100
Subject: Ciao
To: flawless-ad@chevuoida.me

teeeeeeeeeeeest

teeeeeeeeeeeest
teeeeeeeeeeeestteeeeeeeeeeeestteeeeeeeeeeeest
<script>alert(1)</script>
.
EOF

echo "$DATA" | "nc" -C -v "localhost" "1025"