
# Build backend
FROM golang:1.18.0-alpine as backend
WORKDIR /app
COPY . .
RUN go build -o ephimail cmd/main.go

# Build frontend
FROM node:18 as frontend
WORKDIR /app
COPY frontend/ .
RUN npm install
RUN npm run build

# Final image
FROM alpine:3.14
WORKDIR /app
COPY --from=backend /app/ephimail .
COPY --from=frontend /app/dist ./frontend/dist
ENTRYPOINT [ "./ephimail" ]